# Target name
TARGET=micom_grid

# Preprocessor defines
MYCPPDEFS=""

# Fortran compiler
FC=ifort

# C compiler
CC=icc

# Linker
LD=$(FC)

# Paths to netCDF and hdf5 libraries
#NETCDF_DIR=$(CRAY_NETCDF_DIR)/netcdf-pgi
#HDF5_DIR=$(CRAY_HDF5_DIR)/hdf5-pgi
NETCDF_DIR=/cluster/software/netCDF/4.4.1.1-intel-2018a-HDF5-1.8.19
#NETCDF_DIR=/cluster/software/netCDF/4.6.1-intel-2018b

# Include directory for modules
MODINC=-I$(NETCDF_DIR)/include

# Directory list to search for library files
LIBS=-L$(NETCDF_DIR)/lib64 -lnetcdf -lnetcdff

# Include directory for modules
#MODINC=-I$(NETCDF_DIR)/include

# External names
EXTNAME=

# Preprocessor flags
CPPFLAGS=

# Compiler flags
FFLAGS=-r8 -O0 -qno-opt-dynamic-align  -convert big_endian -assume byterecl\
       -mcmodel medium -shared-intel\
       -ftz -traceback -assume realloc_lhs -fp-model source\
       $(EXTNAME) $(MODINC)

SFFLAGS=
SF90FLAGS=

CFLAGS=-qno-opt-dynamic-align -fp-model precise -std=gnu99
 
#
# Linker flags
LDFLAGS=-g $(LIBS)

all: $(TARGET)
depend:
	./mkmf -c $(MYCPPDEFS) -f -p $(TARGET) -t Makefile.config $(TDLIST)
